import 'package:flutter/material.dart';
import '../services/database_service.dart';
import '../services/alokasi_tbs_service.dart';

class AlokasiTbsScreen extends StatefulWidget { final Map<String,dynamic> tiket; const AlokasiTbsScreen({super.key,required this.tiket}); @override State<AlokasiTbsScreen> createState()=>_AlokasiTbsState(); }
class _AlokasiTbsState extends State<AlokasiTbsScreen> {
 final service=AlokasiTbsService(); final db=DB.i; List<Map<String,dynamic>> rows=[],blok=[],grup=[],pemanen=[]; double total=0;
 @override void initState(){super.initState();load();}
 Future<void> load() async { final d=await db.db; final b=await d.query('blok',orderBy:'kode'); final g=await d.query('grup',orderBy:'kode'); final p=await d.query('pemanen',orderBy:'kode'); final a=await service.list(widget.tiket['id'] as int); final t=await service.total(widget.tiket['id'] as int); if(!mounted)return; setState(()=>{blok=b,grup=g,pemanen=p,rows=a,total=t}); }
 double get batas=>(widget.tiket['netto_bersih_kg'] as num?)?.toDouble()??0; double get sisa=>(batas-total).clamp(0,double.infinity);
 void msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 Future<void> tambah() async { if(blok.isEmpty){msg('Belum ada data blok. Isi Data Master > Blok terlebih dahulu.');return;} final berat=TextEditingController(); final jjg=TextEditingController(); int blokId=blok.first['id'] as int; int? grupId; int? pemanenId;
 final ok=await showDialog<bool>(context:context,builder:(dc)=>StatefulBuilder(builder:(c,setLocal)=>AlertDialog(title:const Text('Tambah Alokasi TBS'),content:SizedBox(width:420,child:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<int>(value:blokId,decoration:const InputDecoration(labelText:'Blok'),items:blok.map((x)=>DropdownMenuItem(value:x['id'] as int,child:Text('${x['kode']??''} - ${x['nama']??''}'))).toList(),onChanged:(v){if(v!=null)setLocal(()=>blokId=v);}),DropdownButtonFormField<int?>(value:grupId,decoration:const InputDecoration(labelText:'Grup (opsional)'),items:[const DropdownMenuItem<int?>(value:null,child:Text('— Tidak dipilih —')),...grup.map((x)=>DropdownMenuItem<int?>(value:x['id'] as int,child:Text('${x['kode']??''} - ${x['nama']??''}')))],onChanged:(v)=>setLocal(()=>grupId=v)),DropdownButtonFormField<int?>(value:pemanenId,decoration:const InputDecoration(labelText:'Pemanen (opsional)'),items:[const DropdownMenuItem<int?>(value:null,child:Text('— Tidak dipilih —')),...pemanen.map((x)=>DropdownMenuItem<int?>(value:x['id'] as int,child:Text('${x['kode']??''} - ${x['nama']??''}')))],onChanged:(v)=>setLocal(()=>pemanenId=v)),TextField(controller:berat,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'Berat (kg)',helperText:'Sisa tiket: ${sisa.toStringAsFixed(0)} kg')),TextField(controller:jjg,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Jumlah janjang (opsional)'))]))),actions:[TextButton(onPressed:()=>Navigator.pop(dc,false),child:const Text('Batal')),FilledButton(onPressed:()=>Navigator.pop(dc,true),child:const Text('Tambah'))])));
 final kg=double.tryParse(berat.text.replaceAll(',','.'))??0; final j=int.tryParse(jjg.text)??0; berat.dispose();jjg.dispose(); if(ok!=true)return; try{await service.add(tiketId:widget.tiket['id'] as int,blokId:blokId,grupId:grupId,pemanenId:pemanenId,beratKg:kg,jjg:j);await load();}catch(e){msg(e.toString().replaceFirst('Exception: ',''));} }
 Future<void> hapus(int id)async{await service.delete(id);await load();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('Alokasi • ${widget.tiket['nomor_tiket']}')),floatingActionButton:sisa>0.001?FloatingActionButton.extended(onPressed:tambah,icon:const Icon(Icons.add),label:const Text('Tambah Alokasi')):null,body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:const Icon(Icons.scale),title:Text('Berat bersih: ${batas.toStringAsFixed(0)} kg'),subtitle:Text('Dialokasikan: ${total.toStringAsFixed(0)} kg • Sisa: ${sisa.toStringAsFixed(0)} kg'))),if(rows.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(24),child:Center(child:Text('Belum ada alokasi untuk tiket ini.')))),...rows.map((r)=>Card(child:ListTile(leading:const Icon(Icons.agriculture),title:Text('${r['blok_kode']??''} • ${(r['alokasi_kg'] as num).toStringAsFixed(0)} kg'),subtitle:Text('Grup: ${r['grup_nama']??'-'} • Pemanen: ${r['pemanen_nama']??'-'}'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>hapus(r['id'] as int)))))]));
}
